2022-09-16 20:37:00 UTC-05 | INFO MongoDB - Connected to database: genshin
2022-09-16 20:37:00 UTC-05 | INFO logging in using static token
2022-09-16 20:37:01 UTC-05 | INFO Shard ID None has connected to Gateway (Session ID: 8399864b80963d470cabc4f2df35b0b3).
2022-09-16 20:37:04 UTC-05 | INFO Logged in as
2022-09-16 20:37:04 UTC-05 | INFO ReyBot
2022-09-16 20:37:04 UTC-05 | INFO 327234083815948300
2022-09-16 20:37:22 UTC-05 | INFO None
2022-09-16 20:37:22 UTC-05 | INFO None
2022-09-16 20:37:22 UTC-05 | INFO None
2022-09-16 20:37:29 UTC-05 | INFO MongoDB - Disconnected from database: genshin
2022-09-16 20:37:29 UTC-05 | ERROR Exception ignored in:
2022-09-16 20:37:29 UTC-05 | ERROR <function _ProactorBasePipeTransport.__del__ at 0x000002CBDCFF23B0>
2022-09-16 20:37:29 UTC-05 | ERROR Traceback (most recent call last):
2022-09-16 20:37:29 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
2022-09-16 20:37:29 UTC-05 | ERROR self.close()
2022-09-16 20:37:29 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
2022-09-16 20:37:29 UTC-05 | ERROR self._loop.call_soon(self._call_connection_lost, None)
2022-09-16 20:37:29 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
2022-09-16 20:37:29 UTC-05 | ERROR self._check_closed()
2022-09-16 20:37:29 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
2022-09-16 20:37:29 UTC-05 | ERROR raise RuntimeError('Event loop is closed')
2022-09-16 20:37:29 UTC-05 | ERROR RuntimeError
2022-09-16 20:37:29 UTC-05 | ERROR :
2022-09-16 20:37:29 UTC-05 | ERROR Event loop is closed
2022-09-16 20:37:52 UTC-05 | INFO MongoDB - Connected to database: genshin
2022-09-16 20:37:52 UTC-05 | INFO logging in using static token
2022-09-16 20:37:54 UTC-05 | INFO Shard ID None has connected to Gateway (Session ID: 31046629ffc5b2715186017e2eda38cd).
2022-09-16 20:38:04 UTC-05 | INFO Logged in as
2022-09-16 20:38:04 UTC-05 | INFO ReyBot
2022-09-16 20:38:04 UTC-05 | INFO 327234083815948300
2022-09-16 20:38:07 UTC-05 | INFO {'timestamp': '2022-09-17T01:10:01.650Z', 'startTime': '2022-09-17T00:00:01.000Z', 'round': 4, 'world': 17, 'outfitWarId': 36, 'roundId': '339330750175086918', 'order': 0, 'instanceId': None, 'outfit': {'id': '37565159127660775', 'name': 'GOBLIN JUMPERS', 'faction': 2, 'world': 17, 'leader': '5428901346097237505', 'tag': 'GOB'}, 'rankingParameters': {'TotalScore': 31198, 'MatchesPlayed': 3, 'Wins': 3, 'Losses': 0, 'TiebreakerPoints': 1198, 'FactionRank': None, 'GlobalRank': 22}}
2022-09-16 20:38:07 UTC-05 | INFO {'timestamp': '2022-09-17T01:10:01.650Z', 'startTime': '2022-09-17T00:00:01.000Z', 'round': 4, 'world': 17, 'outfitWarId': 36, 'roundId': '339330750175086918', 'order': 9, 'instanceId': None, 'outfit': {'id': '37585771050324328', 'name': 'Hatsune Miku Project Nexus', 'faction': 3, 'world': 17, 'leader': '5429231137008437233', 'tag': 'MlKU'}, 'rankingParameters': {'TotalScore': 20950, 'MatchesPlayed': 3, 'Wins': 2, 'Losses': 1, 'TiebreakerPoints': 950, 'FactionRank': None, 'GlobalRank': 13}}
2022-09-16 20:38:07 UTC-05 | INFO {'timestamp': '2022-09-17T01:10:01.650Z', 'startTime': '2022-09-17T00:00:01.000Z', 'round': 4, 'world': 17, 'outfitWarId': 36, 'roundId': '339330750175086918', 'order': 8, 'instanceId': None, 'outfit': {'id': '37567362753118636', 'name': 'NeoLuxEterna', 'faction': 2, 'world': 17, 'leader': '5428011263345421425', 'tag': 'NLUX'}, 'rankingParameters': {'TotalScore': 10604, 'MatchesPlayed': 3, 'Wins': 1, 'Losses': 2, 'TiebreakerPoints': 604, 'FactionRank': None, 'GlobalRank': 14}}
2022-09-16 20:38:26 UTC-05 | INFO MongoDB - Disconnected from database: genshin
2022-09-16 20:38:43 UTC-05 | INFO MongoDB - Connected to database: genshin
2022-09-16 20:38:43 UTC-05 | INFO logging in using static token
2022-09-16 20:38:44 UTC-05 | INFO Shard ID None has connected to Gateway (Session ID: a74d59b8b852f29e3e9d1a4bb2b9a9d7).
2022-09-16 20:39:04 UTC-05 | INFO Logged in as
2022-09-16 20:39:04 UTC-05 | INFO ReyBot
2022-09-16 20:39:04 UTC-05 | INFO 327234083815948300
2022-09-16 20:39:09 UTC-05 | INFO {'timestamp': '2022-09-17T01:10:01.650Z', 'startTime': '2022-09-17T00:00:01.000Z', 'round': 4, 'world': 17, 'outfitWarId': 36, 'roundId': '339330750175086918', 'order': 0, 'instanceId': None, 'outfit': {'id': '37565159127660775', 'name': 'GOBLIN JUMPERS', 'faction': 2, 'world': 17, 'leader': '5428901346097237505', 'tag': 'GOB'}, 'rankingParameters': {'TotalScore': 31198, 'MatchesPlayed': 3, 'Wins': 3, 'Losses': 0, 'TiebreakerPoints': 1198, 'FactionRank': None, 'GlobalRank': 22}}
2022-09-16 20:39:09 UTC-05 | INFO {'timestamp': '2022-09-17T01:10:01.650Z', 'startTime': '2022-09-17T00:00:01.000Z', 'round': 4, 'world': 17, 'outfitWarId': 36, 'roundId': '339330750175086918', 'order': 9, 'instanceId': None, 'outfit': {'id': '37585771050324328', 'name': 'Hatsune Miku Project Nexus', 'faction': 3, 'world': 17, 'leader': '5429231137008437233', 'tag': 'MlKU'}, 'rankingParameters': {'TotalScore': 20950, 'MatchesPlayed': 3, 'Wins': 2, 'Losses': 1, 'TiebreakerPoints': 950, 'FactionRank': None, 'GlobalRank': 13}}
2022-09-16 20:39:09 UTC-05 | INFO {'timestamp': '2022-09-17T01:10:01.650Z', 'startTime': '2022-09-17T00:00:01.000Z', 'round': 4, 'world': 17, 'outfitWarId': 36, 'roundId': '339330750175086918', 'order': 8, 'instanceId': None, 'outfit': {'id': '37567362753118636', 'name': 'NeoLuxEterna', 'faction': 2, 'world': 17, 'leader': '5428011263345421425', 'tag': 'NLUX'}, 'rankingParameters': {'TotalScore': 10604, 'MatchesPlayed': 3, 'Wins': 1, 'Losses': 2, 'TiebreakerPoints': 604, 'FactionRank': None, 'GlobalRank': 14}}
2022-09-16 20:41:37 UTC-05 | INFO MongoDB - Disconnected from database: genshin
2022-09-16 20:44:03 UTC-05 | INFO MongoDB - Connected to database: genshin
2022-09-16 20:44:03 UTC-05 | INFO logging in using static token
2022-09-16 20:44:04 UTC-05 | INFO Shard ID None has connected to Gateway (Session ID: 61a78ed329b21c38da5c7ea1281a88f4).
2022-09-16 20:44:07 UTC-05 | INFO Logged in as
2022-09-16 20:44:07 UTC-05 | INFO ReyBot
2022-09-16 20:44:07 UTC-05 | INFO 327234083815948300
2022-09-16 20:44:25 UTC-05 | ERROR An exception has ocurred while executing the bot:
2022-09-16 20:44:25 UTC-05 | ERROR Traceback (most recent call last):
2022-09-16 20:44:25 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 851, in _do_call
2022-09-16 20:44:25 UTC-05 | ERROR     return await self._callback(interaction, **params)  # type: ignore
2022-09-16 20:44:25 UTC-05 | ERROR   File "d:\Users\Juan PC\Documents\Programming Scripts\Python Scripts\BWAE\ReyBot\bot.py", line 346, in getOWMatches
2022-09-16 20:44:25 UTC-05 | ERROR     embed = getOWEmbed(pages[current_page-1], server, current_page, len(pages))
2022-09-16 20:44:25 UTC-05 | ERROR   File "d:\Users\Juan PC\Documents\Programming Scripts\Python Scripts\BWAE\ReyBot\discord_tools\embeds.py", line 147, in getOWEmbed
2022-09-16 20:44:25 UTC-05 | ERROR     matchNumber //= 2
2022-09-16 20:44:25 UTC-05 | ERROR TypeError: unsupported operand type(s) for //=: 'str' and 'int'
2022-09-16 20:44:25 UTC-05 | ERROR 
2022-09-16 20:44:25 UTC-05 | ERROR The above exception was the direct cause of the following exception:
2022-09-16 20:44:25 UTC-05 | ERROR Traceback (most recent call last):
2022-09-16 20:44:25 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\tree.py", line 1240, in _call
2022-09-16 20:44:25 UTC-05 | ERROR     await command._invoke_with_namespace(interaction, namespace)
2022-09-16 20:44:25 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 876, in _invoke_with_namespace
2022-09-16 20:44:25 UTC-05 | ERROR     return await self._do_call(interaction, transformed_values)
2022-09-16 20:44:25 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 865, in _do_call
2022-09-16 20:44:25 UTC-05 | ERROR     raise CommandInvokeError(self, e) from e
2022-09-16 20:44:25 UTC-05 | ERROR discord.app_commands.errors.CommandInvokeError: Command 'get_ow_matches' raised an exception: TypeError: unsupported operand type(s) for //=: 'str' and 'int'
2022-09-16 20:44:26 UTC-05 | ERROR An exception has ocurred while executing the bot:
2022-09-16 20:44:26 UTC-05 | ERROR Traceback (most recent call last):
2022-09-16 20:44:26 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 851, in _do_call
2022-09-16 20:44:26 UTC-05 | ERROR     return await self._callback(interaction, **params)  # type: ignore
2022-09-16 20:44:26 UTC-05 | ERROR   File "d:\Users\Juan PC\Documents\Programming Scripts\Python Scripts\BWAE\ReyBot\bot.py", line 346, in getOWMatches
2022-09-16 20:44:26 UTC-05 | ERROR     embed = getOWEmbed(pages[current_page-1], server, current_page, len(pages))
2022-09-16 20:44:26 UTC-05 | ERROR   File "d:\Users\Juan PC\Documents\Programming Scripts\Python Scripts\BWAE\ReyBot\discord_tools\embeds.py", line 147, in getOWEmbed
2022-09-16 20:44:26 UTC-05 | ERROR     matchNumber //= 2
2022-09-16 20:44:26 UTC-05 | ERROR TypeError: unsupported operand type(s) for //=: 'str' and 'int'
2022-09-16 20:44:26 UTC-05 | ERROR 
2022-09-16 20:44:26 UTC-05 | ERROR The above exception was the direct cause of the following exception:
2022-09-16 20:44:26 UTC-05 | ERROR Traceback (most recent call last):
2022-09-16 20:44:26 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\tree.py", line 1089, in wrapper
2022-09-16 20:44:26 UTC-05 | ERROR     await self._call(interaction)
2022-09-16 20:44:26 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\tree.py", line 1244, in _call
2022-09-16 20:44:26 UTC-05 | ERROR     await self.on_error(interaction, e)
2022-09-16 20:44:26 UTC-05 | ERROR   File "d:\Users\Juan PC\Documents\Programming Scripts\Python Scripts\BWAE\ReyBot\bot.py", line 119, in on_app_command_error
2022-09-16 20:44:26 UTC-05 | ERROR     raise error
2022-09-16 20:44:26 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\tree.py", line 1240, in _call
2022-09-16 20:44:26 UTC-05 | ERROR     await command._invoke_with_namespace(interaction, namespace)
2022-09-16 20:44:26 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 876, in _invoke_with_namespace
2022-09-16 20:44:26 UTC-05 | ERROR     return await self._do_call(interaction, transformed_values)
2022-09-16 20:44:26 UTC-05 | ERROR   File "D:\Users\Juan PC\AppData\Roaming\Python\Python310\lib\site-packages\discord\app_commands\commands.py", line 865, in _do_call
2022-09-16 20:44:26 UTC-05 | ERROR     raise CommandInvokeError(self, e) from e
2022-09-16 20:44:26 UTC-05 | ERROR discord.app_commands.errors.CommandInvokeError: Command 'get_ow_matches' raised an exception: TypeError: unsupported operand type(s) for //=: 'str' and 'int'
2022-09-16 20:45:14 UTC-05 | INFO MongoDB - Disconnected from database: genshin
2022-09-16 20:45:19 UTC-05 | INFO MongoDB - Connected to database: genshin
2022-09-16 20:45:19 UTC-05 | INFO logging in using static token
2022-09-16 20:45:20 UTC-05 | INFO Shard ID None has connected to Gateway (Session ID: d3b4660ebca5105abaa694d10c47a1fc).
2022-09-16 20:45:23 UTC-05 | INFO Logged in as
2022-09-16 20:45:23 UTC-05 | INFO ReyBot
2022-09-16 20:45:23 UTC-05 | INFO 327234083815948300
2022-09-16 20:45:51 UTC-05 | INFO MongoDB - Disconnected from database: genshin
2022-09-16 20:46:03 UTC-05 | INFO MongoDB - Connected to database: genshin
2022-09-16 20:46:03 UTC-05 | INFO logging in using static token
2022-09-16 20:46:04 UTC-05 | INFO Shard ID None has connected to Gateway (Session ID: 78ee1bef909142ec2fcb4fa5d348798f).
2022-09-16 20:46:23 UTC-05 | INFO Logged in as
2022-09-16 20:46:23 UTC-05 | INFO ReyBot
2022-09-16 20:46:23 UTC-05 | INFO 327234083815948300
2022-09-16 20:47:00 UTC-05 | INFO MongoDB - Disconnected from database: genshin
